### ISSUE TITLE
Annoying Jump when restarting

### ISSUE THREAD

**Issue by giraugh** [retroverse/Hex#18]
especially noticeable when using auto restart.

**Comment by giraugh** [comment]
if anyone can come up with a good way to do this it would be appreciated
the only thing i can think of is finding a way to keep the bot properties loaded when restarting but i can't remember where they are reset/set to the default.

**Comment by Hazelfire** [comment]
I'll look into it for you!

**Comment by giraugh** [comment]
Thanks!

**Comment by Hazelfire** [comment]
Done!!!

That's the last issue, just one nasty line

**Comment by giraugh** [comment]
Yay!
